apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-content-${cat-name}
  namespace: default
data:
  index.html: |
    My name is ${cat-name}
---
apiVersion: v1
kind: Pod
metadata:
  name: ${cat-name}
  labels:
    app: ${cat-name}
spec:
  containers:
    - name: nginx
      image: ${cat-image}
      ports:
        - containerPort: 80
      volumeMounts:
        - name: content-volume-${cat-name}
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumes:
    - name: content-volume-${cat-name}
      configMap:
        name: nginx-content-${cat-name}
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-${cat-name}-service
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: ${cat-name}
  type: NodePort
