apiVersion: v1
kind: ServiceAccount
metadata:
  name: cat-operator-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
  - kind: ServiceAccount
    name: cat-operator-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: cat-operator-secret
  annotations:
    kubernetes.io/service-account.name: cat-operator-service-account
type: kubernetes.io/service-account-token